name: user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  supabase_flutter: ^2.8.3
  file_picker: ^9.0.0
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  flutter_stripe: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
